version: "3.8"

services:
  frontend:
    build:
      context: ./
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_BASE_URL=http://localhost:4000
    depends_on:
      - backend

  backend:
    build:
      context: ../GeoTalk/
    ports:
      - "4000:4000"
    expose:
      - "4000"
    environment:
      - ALLOWED_ORIGIN=http://localhost:3000
      - REDIS_URL=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
